version: "3.6" 

services:
    sqlite:

      container_name: sqlite-container

      restart: always

      build:
        context: .
        dockerfile: ./Dockerfile

      volumes:
        - ./db:/var/lib/sqlite

      tty: true

volumes:
  db:

